#     Partie 1 – Exploration des données

1) Charger les données CSV

- Installation et Importation des bibliothèques nécessaire à la réalisation de cet atelier

In [2]:
%pip install pandas numpy matplotlib seaborn scikit-learn

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bmd\onedrive\bureau\atelier_prepa_donnees_tab\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.65.0-cp314-cp314-win_amd64.whl.metadata (127 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\bmd\onedrive\bureau\atelier_prepa_donnees_tab\.venv\lib\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: six>=1.5 in c:\users\bmd\onedrive\bureau\atelier_prepa_donnees_tab\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.8 MB 6.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.8 MB 11.0 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.8 MB 12.0 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 12.1 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 11.6 MB/s  0:00:00
Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   --------- ------------------------------ 2.9/12.7 MB 13.9 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.7 MB 13.7 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.7 MB 13.7 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.7 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 13.0 MB/s  0:00:00
Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ------------ --------------------------- 2.9/9.5 MB 14.7 MB/s eta 0:00:01
   ------------------------- -------------- 6.0/9.5 MB 14.4 MB/s eta 0:00:01
   ----------------------------------- ---- 8.4/9.5 MB 14.0 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 10.7 MB/s  0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading scikit_learn-1.9.1-cp314-cp314-win_amd64.whl (8.4 MB)
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ----------- ---------------------------- 2.4/8.4 MB 12.1 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.4 MB 12.4 MB/s eta 0:00:01
   ------------------------------------- -- 7.9/8.4 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------- 8.4/8.4 MB 12.2 MB/s  0:00:00
Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl (240 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.65.0-cp314-cp314-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 2.5/2.5 MB 11.6 MB/s  0:00:00
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl (72 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl (37.4 MB)
   ---------------------------------------- 0.0/37.4 MB ? eta -:--:--
   -- ------------------------------------- 2.6/37.4 MB 13.1 MB/s eta 0:00:03
   ----- ---------------------------------- 5.2/37.4 MB 12.7 MB/s eta 0:00:03
   -------- ------------------------------- 8.1/37.4 MB 13.0 MB/s eta 0:00:03
   ----------- ---------------------------- 11.0/37.4 MB 13.2 MB/s eta 0:00:03
   -------------- ------------------------- 13.9/37.4 MB 13.3 MB/s eta 0:00:02
   ------------------ --------------------- 17.0/37.4 MB 13.5 MB/s eta 0:00:02
   --------------------- ------------------ 20.2/37.4 MB 13.6 MB/s eta 0:00:02
   ------------------------ --------------- 23.3/37.4 MB 13.7 MB/s eta 0:00:02
   ---------------------------- ----------- 26.2/37.4 MB 13.7 MB/s eta 0:00:01
   ------------------------------ --------- 28.8/37.4 MB 13.5 MB/s eta 0:00:01
   --------------------------------- ------ 31.7/37.4 MB 13.5 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/37.4 MB 13.5 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.4 MB 13.5 MB/s eta 0:00:01
   ---------------------------------------- 37.4/37.4 MB 12.9 MB/s  0:00:02
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, threadpoolctl, pyparsing, pillow, numpy, narwhals, kiwisolver, fonttools, cycler, cloudpickle, scipy, pandas, joblib, contourpy, scikit-learn, matplotlib, seaborn

   ----------------------------------------  0/17 [tzdata]
   ----------------------------------------  0/17 [tzdata]
   ----------------------------------------  0/17 [tzdata]
   ----------------------------------------  0/17 [tzdata]
   ----------------------------------------  0/17 [tzdata]
   ----------------------------------------  0/17 [tzdata]
   ----------------------------------------  0/17 [tzdata]
   ----------------------------------------  0/17 [tzdata]
   ----------------------------------------  0/17 [tzdata]
   ----------------------------------------  0/17 [tzdata]
   -- -------------------------------------  1/17 [threadpoolctl]
   ---- -----------------------------------  2/17 [pyparsing]
   ---- -----------------------------------  2/17 [pyparsing]
   ---- -----------------------------------  2/17 [pyparsing]
   ---- -----------------------------------  2/17 [pyparsing]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   ------- --------------------------------  3/17 [pillow]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   --------- ------------------------------  4/17 [numpy]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   -------------- -------------------------  6/17 [kiwisolver]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]
   ---------------- -----------------------  7/17 [fonttools]

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("../data/smart_building_raw.csv")

2) Afficher les premières lignes du dataset ;

In [6]:
df.head(5)

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

3) Afficher les dernières lignes du dataset ;

In [7]:
df.tail(5)

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

4) Combien d'observations contient le dataset ?

In [9]:
df.shape

(507, 14)

5) Combien de variables possède le dataset ?

In [11]:
df.shape[1]
print("Le mombre de variables est de :" , df.shape[1])

Le mombre de variables est de : 14

6) Identifier les variables numériques ;

In [14]:
variables_numeriques = df.select_dtypes(include=np.number).columns
print("variables_numeriques : ", variables_numeriques)

variables_numeriques :  Index(['id_mesure', 'temperature', 'humidite', 'co2', 'occupation',
       'consommation_kwh'],
      dtype='str')

7) Identifier les variables catégorielles ;

In [16]:
variables_categorielles = df.select_dtypes(include="object").columns
print("variables_categorielles : ", variables_categorielles)

variables_categorielles :  Index(['date', 'batiment', 'type_batiment', 'zone', 'mode_climatisation',
       'etat_systeme', 'jour_semaine', 'alerte'],
      dtype='str')

C:\Users\bmd\AppData\Local\Temp\ipykernel_18652\1779963292.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  variables_categorielles = df.select_dtypes(include="object").columns

8) Identifier les dates

In [20]:
variables_dates = df.select_dtypes(include=["datetime"]).columns

print("Variables de type date :", variables_dates)
# print(variables_dates)

Variables de type date : Index([], dtype='str')

9) Identifier les identifiants

In [ ]:
print(df.columns.tolist())

Index([], dtype='str')

In [23]:
df.nunique()

id_mesure             500
date                  500
batiment                8
type_batiment          16
zone                    4
temperature           144
humidite              305
co2                   392
occupation            108
consommation_kwh      445
mode_climatisation      7
etat_systeme            3
jour_semaine            7
alerte                  2
dtype: int64

10) Déterminer les statistiques : moyenne, médiane, minimum, maximum, écart-type et quartiles.

In [24]:
df.describe()

,id_mesure,temperature,humidite,co2,occupation,consommation_kwh
count,507.000000,495.000000,496.000000,500.000000,501.000000,502.000000
mean,1251.114398,24.154141,57.864113,844.150000,44.850299,169.069323
std,144.782769,7.418465,16.026336,582.181386,24.949139,53.164294
min,1001.000000,-30.000000,-12.000000,89.000000,-20.000000,-100.000000
25%,1125.500000,21.600000,49.275000,623.750000,27.000000,136.875000
50%,1252.000000,24.000000,57.550000,787.500000,46.000000,169.800000
75%,1376.500000,26.000000,65.750000,952.000000,61.000000,202.975000
max,1500.000000,96.000000,160.000000,6000.000000,116.000000,336.200000

11) Y a-t-il des variables potentiellement problématiques ?

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_mesure           507 non-null    int64
 1   date                507 non-null    str
 2   batiment            507 non-null    str
 3   type_batiment       503 non-null    str
 4   zone                507 non-null    str
 5   temperature         495 non-null    float64
 6   humidite            496 non-null    float64
 7   co2                 500 non-null    float64
 8   occupation          501 non-null    float64
 9   consommation_kwh    502 non-null    float64
 10  mode_climatisation  502 non-null    str
 11  etat_systeme        507 non-null    str
 12  jour_semaine        502 non-null    str
 13  alerte              507 non-null    str
dtypes: float64(5), int64(1), str(8)
memory usage: 55.6 KB

Oui il existe des variables problematiques notamment pour les varaiables temperatures, humidite,

12) Pour les données incohérentes :

a) rechercher des valeurs telles que humidité < 0 ;

In [27]:
df[df.humidite <0]

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
281,1126,2025-02-01 06:00:00,B2,École,D,24.8,-5.0,759.0,57.0,225.2,Boost,Normal,Samedi,Non
335,1036,2025-01-09 18:00:00,B4,Bureau,D,21.2,-8.0,160.0,25.0,120.2,Normal,Alerte,Jeudi,Non
366,1216,2025-02-23 18:00:00,B3,Hôpital,B,23.2,-12.0,702.0,41.0,119.8,Normal,Normal,Dimanche,Non

b) rechercher des valeurs telles que humidité > 100 ;

In [28]:
df[df.humidite >100]

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
59,1246,2025-03-03 06:00:00,B5,Centre commercial,A,24.2,108.0,813.0,18.0,-15.0,Normal,Normal,Lundi,Non
103,1016,2025-01-04 18:00:00,B6,Université,B,26.9,145.0,670.0,28.0,175.9,Normal,Normal,Samedi,Non
128,1156,2025-02-08 18:00:00,B1,Bureau,A,NaN,160.0,941.0,37.0,149.8,Eco,Normal,Samedi,Oui
160,1186,2025-02-16 06:00:00,B8,Entrepôt,B,24.9,125.0,NaN,18.0,123.5,Normal,Normal,Dimanche,Non
268,1276,2025-03-10 18:00:00,B1,Bureau,D,26.0,140.0,633.0,25.0,148.3,Normal,Normal,Lundi,Non
327,1066,2025-01-17 06:00:00,B2,École,C,25.8,132.0,646.0,14.0,93.6,Eco,Normal,Vendredi,Non
342,1096,2025-01-24 18:00:00,B8,Entrepôt,A,20.3,110.0,783.0,55.0,121.0,Normal,Normal,Vendredi,Non